default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: zapmail_development
test:
  <<: *default
  database: zapmail_test


production:
  primary: &primary_production
    <<: *default
    database: zapmail_production
    username: zapmail
    password: <%= ENV["ZAPMAIL_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: zapmail_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: zapmail_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: zapmail_production_cable
    migrations_paths: db/cable_migrate
